version: "3.9"

services:
  web:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
  worker:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && celery -A config worker -l info"
    env_file:
      - .env
    depends_on:
      - redis
  beat:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && celery -A config beat -l info"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
